### ISSUE TITLE
输入位置

### ISSUE THREAD

**Issue by zhangzhangthink** [LXP-Never/FLGCCRN#1]
凌逆战老师您好，十分感谢您对许多有关语音增强文献的翻译与整理，您的文献翻译以及您复现的代码对我非常有用，但我作为一个刚学习该领域的小白，想请教一下：我在您本篇文章的代码中没有找到输入语音数据的地方，即我不知道怎么将我现有的数据输入到您的网络中，恕我愚笨，希望能得到您的指点。十分感谢！

**Comment by LXP-Never** [comment]
我只开源了模型，需要自己写训练pipline。训练框架对于每一个项目都是大同小异，所以我没有去push这部分代码。
你可以入手一些简单且完整的SE github repository，再回头来参考FLGCNN的模型代码

**Comment by zhangzhangthink** [comment]
谢谢老师的教导，非常感谢！！
